### ISSUE TITLE
Fixing the interactive video overlay issue

### ISSUE THREAD

**Issue by dianakhuang** [Colin-Fredericks/hx-js#1]
Hi! I was asked to help out by James Donald to get the overlay working.

The issue is that the `ui-widget-overlay` element isn't a child of the `hx-popup` element, so these CSS rules aren't getting applied. You're going to want to keep it as `.ui-widget-overlay` and you might need a `!important` to force it to override the existing `.ui-widget-overlay` CSS.

https://github.com/Colin-Fredericks/hx-js/blob/master/hx.css#L511-L516

Excellent choice of music, btw.

**Comment by dianakhuang** [comment]
And I did update the css on edge just to test to make sure it was working.

**Comment by Colin-Fredericks** [comment]
Wonderful, thank you very much! I'll fold that in right now.

Glad you liked the music. :)
